### ISSUE TITLE
Block blocker

### ISSUE THREAD

**Issue by Telesphoreo** [novelmc/converse#10]
We need to disable TNT and explosions ASAP

**Comment by Jodad** [comment]
[BlockListener.zip](https://github.com/novelmc/converse/files/3352444/BlockListener.zip)
Something I just slapped together, will need to be edited.

**Comment by Telesphoreo** [comment]
Right now we are using EssentialsXProtect. I will look into that tonight, but explosions shouldn't happen for now.

**Comment by Telesphoreo** [comment]
Closing this since EssentialsXProtect seems to be working fine. If issues arise with it, we can make our own.
